# Generated by Django 5.1.4 on 2025-01-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titleguesser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='totle',
            new_name='title',
        ),
    ]
