# Generated by Django 5.1.4 on 2025-01-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleguesser', '0002_rename_totle_character_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image',
            field=models.CharField(default='None', max_length=2000),
            preserve_default=False,
        ),
    ]
